<?php
/**
 * ISO 3166-1 alpha-2 country code → human-readable name mapping.
 *
 * Used by admin pages so that pills and optgroup labels show
 * "España" instead of just "ES".
 *
 * @package Hugo\MiPluginAiralo
 */

namespace Hugo\MiPluginAiralo\Support;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

final class Countries {

    private const MAP = [
        'AD' => 'Andorra',
        'AE' => 'Emiratos Árabes Unidos',
        'AF' => 'Afganistán',
        'AG' => 'Antigua y Barbuda',
        'AL' => 'Albania',
        'AM' => 'Armenia',
        'AO' => 'Angola',
        'AR' => 'Argentina',
        'AT' => 'Austria',
        'AU' => 'Australia',
        'AZ' => 'Azerbaiyán',
        'BA' => 'Bosnia y Herzegovina',
        'BB' => 'Barbados',
        'BD' => 'Bangladés',
        'BE' => 'Bélgica',
        'BF' => 'Burkina Faso',
        'BG' => 'Bulgaria',
        'BH' => 'Baréin',
        'BI' => 'Burundi',
        'BJ' => 'Benín',
        'BN' => 'Brunéi',
        'BO' => 'Bolivia',
        'BR' => 'Brasil',
        'BS' => 'Bahamas',
        'BT' => 'Bután',
        'BW' => 'Botsuana',
        'BY' => 'Bielorrusia',
        'BZ' => 'Belice',
        'CA' => 'Canadá',
        'CD' => 'Rep. Dem. del Congo',
        'CF' => 'Rep. Centroafricana',
        'CG' => 'Congo',
        'CH' => 'Suiza',
        'CI' => 'Costa de Marfil',
        'CL' => 'Chile',
        'CM' => 'Camerún',
        'CN' => 'China',
        'CO' => 'Colombia',
        'CR' => 'Costa Rica',
        'CU' => 'Cuba',
        'CV' => 'Cabo Verde',
        'CY' => 'Chipre',
        'CZ' => 'Chequia',
        'DE' => 'Alemania',
        'DJ' => 'Yibuti',
        'DK' => 'Dinamarca',
        'DM' => 'Dominica',
        'DO' => 'Rep. Dominicana',
        'DZ' => 'Argelia',
        'EC' => 'Ecuador',
        'EE' => 'Estonia',
        'EG' => 'Egipto',
        'ER' => 'Eritrea',
        'ES' => 'España',
        'ET' => 'Etiopía',
        'FI' => 'Finlandia',
        'FJ' => 'Fiyi',
        'FM' => 'Micronesia',
        'FR' => 'Francia',
        'GA' => 'Gabón',
        'GB' => 'Reino Unido',
        'GD' => 'Granada',
        'GE' => 'Georgia',
        'GH' => 'Ghana',
        'GM' => 'Gambia',
        'GN' => 'Guinea',
        'GQ' => 'Guinea Ecuatorial',
        'GR' => 'Grecia',
        'GT' => 'Guatemala',
        'GW' => 'Guinea-Bisáu',
        'GY' => 'Guyana',
        'HK' => 'Hong Kong',
        'HN' => 'Honduras',
        'HR' => 'Croacia',
        'HT' => 'Haití',
        'HU' => 'Hungría',
        'ID' => 'Indonesia',
        'IE' => 'Irlanda',
        'IL' => 'Israel',
        'IN' => 'India',
        'IQ' => 'Irak',
        'IR' => 'Irán',
        'IS' => 'Islandia',
        'IT' => 'Italia',
        'JM' => 'Jamaica',
        'JO' => 'Jordania',
        'JP' => 'Japón',
        'KE' => 'Kenia',
        'KG' => 'Kirguistán',
        'KH' => 'Camboya',
        'KI' => 'Kiribati',
        'KM' => 'Comoras',
        'KN' => 'San Cristóbal y Nieves',
        'KR' => 'Corea del Sur',
        'KW' => 'Kuwait',
        'KZ' => 'Kazajistán',
        'LA' => 'Laos',
        'LB' => 'Líbano',
        'LC' => 'Santa Lucía',
        'LI' => 'Liechtenstein',
        'LK' => 'Sri Lanka',
        'LR' => 'Liberia',
        'LS' => 'Lesoto',
        'LT' => 'Lituania',
        'LU' => 'Luxemburgo',
        'LV' => 'Letonia',
        'LY' => 'Libia',
        'MA' => 'Marruecos',
        'MC' => 'Mónaco',
        'MD' => 'Moldavia',
        'ME' => 'Montenegro',
        'MG' => 'Madagascar',
        'MK' => 'Macedonia del Norte',
        'ML' => 'Malí',
        'MM' => 'Myanmar',
        'MN' => 'Mongolia',
        'MO' => 'Macao',
        'MR' => 'Mauritania',
        'MT' => 'Malta',
        'MU' => 'Mauricio',
        'MV' => 'Maldivas',
        'MW' => 'Malaui',
        'MX' => 'México',
        'MY' => 'Malasia',
        'MZ' => 'Mozambique',
        'NA' => 'Namibia',
        'NE' => 'Níger',
        'NG' => 'Nigeria',
        'NI' => 'Nicaragua',
        'NL' => 'Países Bajos',
        'NO' => 'Noruega',
        'NP' => 'Nepal',
        'NR' => 'Nauru',
        'NZ' => 'Nueva Zelanda',
        'OM' => 'Omán',
        'PA' => 'Panamá',
        'PE' => 'Perú',
        'PG' => 'Papúa Nueva Guinea',
        'PH' => 'Filipinas',
        'PK' => 'Pakistán',
        'PL' => 'Polonia',
        'PT' => 'Portugal',
        'PW' => 'Palaos',
        'PY' => 'Paraguay',
        'QA' => 'Catar',
        'RO' => 'Rumanía',
        'RS' => 'Serbia',
        'RU' => 'Rusia',
        'RW' => 'Ruanda',
        'SA' => 'Arabia Saudita',
        'SB' => 'Islas Salomón',
        'SC' => 'Seychelles',
        'SD' => 'Sudán',
        'SE' => 'Suecia',
        'SG' => 'Singapur',
        'SI' => 'Eslovenia',
        'SK' => 'Eslovaquia',
        'SL' => 'Sierra Leona',
        'SM' => 'San Marino',
        'SN' => 'Senegal',
        'SO' => 'Somalia',
        'SR' => 'Surinam',
        'SS' => 'Sudán del Sur',
        'ST' => 'Santo Tomé y Príncipe',
        'SV' => 'El Salvador',
        'SY' => 'Siria',
        'SZ' => 'Esuatini',
        'TD' => 'Chad',
        'TG' => 'Togo',
        'TH' => 'Tailandia',
        'TJ' => 'Tayikistán',
        'TL' => 'Timor-Leste',
        'TM' => 'Turkmenistán',
        'TN' => 'Túnez',
        'TO' => 'Tonga',
        'TR' => 'Turquía',
        'TT' => 'Trinidad y Tobago',
        'TV' => 'Tuvalu',
        'TW' => 'Taiwán',
        'TZ' => 'Tanzania',
        'UA' => 'Ucrania',
        'UG' => 'Uganda',
        'US' => 'Estados Unidos',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistán',
        'VA' => 'Ciudad del Vaticano',
        'VC' => 'San Vicente y las Granadinas',
        'VE' => 'Venezuela',
        'VN' => 'Vietnam',
        'VU' => 'Vanuatu',
        'WS' => 'Samoa',
        'XK' => 'Kosovo',
        'YE' => 'Yemen',
        'ZA' => 'Sudáfrica',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabue',
    ];

    /**
     * Returns the human-readable name for an ISO 3166-1 alpha-2 code,
     * or the raw code if not found.
     */
    public static function name( string $code ): string {
        $code = strtoupper( trim( $code ) );
        return self::MAP[ $code ] ?? $code;
    }

    /**
     * Returns the full map (code → name).
     */
    public static function all(): array {
        return self::MAP;
    }
}
